# Generated by Django 2.0.2 on 2018-06-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0002_auto_20180620_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend_list',
            field=models.ManyToManyField(to='User_base.Profile'),
        ),
    ]
