# Generated by Django 2.0.2 on 2018-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0003_auto_20180619_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_preference',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_preference',
            field=models.ManyToManyField(blank=True, to='User_base.Preference'),
        ),
    ]
