# Generated by Django 2.0.2 on 2018-06-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0004_auto_20180620_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to='User_base.Profile'),
        ),
    ]
