# Generated by Django 2.0.2 on 2018-06-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0005_auto_20180620_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='current_user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_preference',
            new_name='preference',
        ),
    ]
