# Generated by Django 2.0.2 on 2018-06-27 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0007_auto_20180627_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='people',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('user', 'people')},
        ),
    ]
