# Generated by Django 2.0.2 on 2018-06-21 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0008_auto_20180621_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='This_user', to='User_base.Profile'),
        ),
    ]
