# Generated by Django 2.0.2 on 2018-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0009_auto_20180621_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(default='Hey there! I am using Makan Mana'),
        ),
    ]
