# Generated by Django 2.0.2 on 2018-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0011_auto_20180621_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, default='Hey there! I am using Makan Mana'),
        ),
    ]
