# Generated by Django 2.0.2 on 2018-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0013_auto_20180621_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to='User_base.Profile'),
        ),
    ]
