# Generated by Django 2.0.2 on 2018-06-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0014_auto_20180621_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='This_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
