# Generated by Django 2.0.2 on 2018-06-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0015_auto_20180621_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='profile',
            new_name='user',
        ),
    ]
